### ISSUE TITLE
Smoother use of react components (entries/chunks) from node_modules

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#102]
Currently, there are a couple of caveats around using entries or imports from folders under `<projectRoot>/node_modules`. 

In `import` statements in (or below) entries, it might be possible to skip the relative `../.. etc ../node_modules` part of the reference - **verify this**. 

In any case it is possible to use relative references to node_modules/x in entryDirs and chunkDirs in react4xp.properties.

However, this could and should be simpler. 

Possible solutions:
- using `node_modules` as default entryDir in itself. Risk: *all* source react components below node_modules will be compiled to assets/react4xp - most likely both wasting build time on compiling assets the developer doesn't need or want, and bloating the artifact, and requiring the developer to rebuild webpack setup for *all* of them in `react4xp.webpack.config.js` lest the build fail. 
- Limiting this by using `node_modules` as a **secondary root for entryDirs/chunkDirs**, the same way `src/main/resources/react4xp` is the current root (but ONLY for each entryDir/chunkDir where the dir exists under `node_modules` and not under `src/main/resources/react4xp`?)
- Whichever of the two options above are chosen: **opt-in or opt-out** for this behavior in react4xp.properties

-----------------------

Different but sort-of-adjacent issue: ready-compiled react component assets might have browser functionality calls compiled in, calls that weren't necessarily part of the source file (in these cases, the react4xp SSR can handle the source file, but not a precompiled asset) - see https://support.enonic.com/hc/en-us/requests/3920?page=1

Currently, if a package changes the location of a react sourcefile internally, the `import`reference will probably break and need to be updated. The suggested solutions above will not solve this.

**Comment by ComLock** [comment]
Will be solved by
https://github.com/enonic/lib-react4xp/issues/778
