### ISSUE TITLE
Support more chunk types than .JS and .CSS

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#103]
Currently, react4xp only handles compiled chunks of type .JS and .CSS (by simply wrapping them in `<script>` and `<link>`). Other chunks will be ignored with error message, or just treated as JS. Font assets, for example, and others, should be supported - or at least possible for developers to fill in handling for.

See React4xp.CLIENT.renderWithDependencies (https://github.com/enonic/react4xp-npm/tree/master/packages/client/src/react4xpClient.es6) for frontend functionality, and buildPageContributions (https://github.com/enonic/lib-react4xp/tree/master/src/main/resources/lib/enonic/react4xp/pageContributions.es6) for XP-side handling.

**Comment by espen42** [comment]
@everyone: when encountering this, please supply examples here - what secondary chunk types have you been unable to get react4xp to handle?

**Comment by espen42** [comment]
https://github.com/enonic/react4xp-build-components/pull/5

**Comment by ComLock** [comment]
Cross that bridge when we get there. If anyone asks for it... What are the examples of this?
