### ISSUE TITLE
Include webpack "plugins" - ready-to-add webpack config modules

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#105]
Some webpack config expansions with rules for compiling commonly needed stuff, would be handy to have included and ready to add in a simple manner?

- [ ] Simple styling, as shown in the docs
- [ ] Styling with CSS modules
- [x] Typescript - TS and TSX

**Comment by espen42** [comment]
Ref: https://github.com/enonic/react4xp-build-components/pull/5

**Comment by ComLock** [comment]
I think TypeScript is supported now. The other things is can be added in the webpack.config.react4xp.js by each app developer, if they need it...
