### ISSUE TITLE
Refreshing a page on SSR after updating app is still too slow 

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#106]
After updating an app while the server is running, the SSR engine restarts and re-caches ALL the basics. This means a 5-10 second delay (edit: or in certain cases much more - resulting in blocking and downtime) before viewing the updates - even if nothing running on the SSR engine was changed.

Implement even lazier lazy-loading? A hash/check for whether assets have changed?

**Comment by espen42** [comment]
Just leaving a note here, a draft for a bigger and better solution. Currently in norwegian, let me know if translation is needed:


Skille serversiderendringa ut i en egen app (app-react4xp-ssr, feks) som lytter på en eller annen URL (config’able) og:
- Tar imot entrynavnet, et props-objekt, en kildekode-streng (kompilert og nashorn-kjørbar react-komponent) og en valgfri content-hash-streng for kildekoden.
- Hvis content-hashen ikke er sendt inn, genereres den internt ut fra kildekodestrengen.
- Hvis entrynavnet og contenthash’en viser at denne reactkomponenten allerede er cachet som en funksjon i SSR-motoren, bare kjøres den funksjonen med props.
- Hvis de ikke er cachet, initialiseres funksjonen i nashorn (som er det trinnet som tar tid), og caches på entrynavn og contenthash - og funksjonen kjøres med props.
- Resultatet av funksjonen er rendret HTML, som returneres i responsen.

Dette er jo en API-definisjon. Så dermed kan utviklere velge om man vil bruke denne appen til det eller implementere sin helt egen rendrings-server hvor som helst (feks i Node hvis man vil, på en helt annen servernode, etc).

Dermed, i den opprinnelige appen m/ react-kildekoden:
- Config’e react4xp til å peke mot en rendrings-server-URL: kanskje som default bruke en service-URL som app-react4xp-ssr har som sin default?
- React4xp starter opp med å lese inn kompilerte react-komponent-assets (entries og chunks), contenthash’er dem og cacher dette på entry/chunk-navnet. Burde kunne gjøres fort. Og her kommer evt lib-static inn i bildet.
- .render sender da disse til rendrings-server-URL’en, får tilbake HTML og håndterer det som i dag.

Evt på lengre sikt:
- Det kan tilogmed gjøres på en sånn måte at hvis URL’en er tom, så bruker react4xp bare dagens system. Da er det bakoverkompatibelt også, docs og lav terskel for å komme i gang kan beholdes, men vi kan legge til et advanced-kapittel i guiden.
- Hvis lib-react4xp skal fortsette å ha sin egen SSR sånn som i dag, kan selve SSR-delen skilles ut som et lib-react4xp-ssr, som både lib-react4xp og app-react4xp-ssr bruker.
- Denne strukturen kan da mye lettere gjenbrukes til feks Vue og andre framtidige visualiseringssystemer. Enda friere for utviklere. Candy!

**Comment by rymsha** [comment]
Switching to GraalVM after #455 should make SSR much faster
