### ISSUE TITLE
<!DOCTYPE html> can't be part of the body parameter

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#107]
If a page controller `React4xp.render`-s into a `<html>...</html>` structure in the `body` option, that body structure can't start with `<!DOCTYPE html>`. This is because the renderer uses an XML parser, and the doctype tag is unclosed and not XML compatible. 

**Current workaround in the starter**: add `<!DOCTYPE html>` to `body` _after_  the rendering, but before returning the SSR'ed string:

```
const output = React4xp.render(
        'Movie',
        props,
        request,
        {
            id,
            body: `
                <html>
                    <head>
                        <meta charset="UTF-8" />
                        <title>${content.displayName}</title>
                    </head>
                    <body class="xp-page">
                        <div id="${id}"></div>
                    </body>
                </html>
            `
        }
    );

    // Workaround:
    output.body = '<!DOCTYPE html>' + output.body;

    return output;
```

Fix: It would be nice if the renderer could check if a serverside-rendered string starts with `<html ` and add `<!DOCTYPE html>` at the end of the rendering before returning it? If so, check: is that a breaking change? What happens to controllers that use the current workaround and add yet another tag like that?

**Comment by sigdestad** [comment]
Be careful about such magic tricks. Rather give example of how to do this manually

**Comment by espen42** [comment]
Next.js' approach, maybe useful: https://youtu.be/mTz0GXj8NN0?t=1675

**Comment by rymsha** [comment]
https://github.com/enonic/lib-react4xp/pull/679 fixed it
