### ISSUE TITLE
React4xp - Discuss handling of htmlArea and processHtml / macros

### ISSUE THREAD

**Issue by sigdestad** [enonic/lib-react4xp#128]
@sigdestad commented on [Fri Nov 06 2020](https://github.com/enonic/lib-explorer/issues/68)

Lets discuss how to handle this - it is also a generic Guillotine problem

**Comment by sigdestad** [comment]
@espen42 - I thought we discussed and concluded something on this topic?

**Comment by sigdestad** [comment]
Was it that this is not a react4XP issue, but a Guillotine issues

**Comment by espen42** [comment]
@sigdestad Yeah, that's correct. Closing this one.
