### ISSUE TITLE
Use lib-static

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#149]
https://enonic.atlassian.net/wiki/spaces/TD/pages/1326972931/lib-static

**Comment by ComLock** [comment]
We can still use a service to serve the "assets", but in the jar file they should NOT be located under assets, but rather (build/resources/main/) /r4xAssets

**Comment by rymsha** [comment]
there is a new version of lib-static 2.0

we should be able to remove all etag handling code

**Comment by alansemenov** [comment]
Done in https://github.com/enonic/lib-react4xp/issues/1454
