### ISSUE TITLE
Split out SSR to app-react4xp-ssr

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#153]
Create an XP app that handles a (key->function cached) continuous nashorn session. 

Service with this API/behavior:

Some parameters, all optional in themselves but at least id or script must be present:
- `script`: string with (nashorn-)runnable JS, usually a string-form compiled react asset which creates one or more ready-to-run component functions in the nashorn engine
- `id`: script identifier. Can be a reacf4xp jsxPath or an asset name etc.
- `hash`: content hash from the script's content. Used together with the `id` as a cache key.
- `props`: arguments to feed into run the function when running it. JSON-stringified object.
- `runOnce`: the script will run only if that keyed (by id+hash) script hasn't been run before. Marks the special setup scripts: externals and nashornpolyfills.

Behavior:
1. If neither script nor id are present, throw/respond with a 400-error message (bad request).

2. If only script is present, run it to produce (a) ready-to-run function(s) in nashorn.
  A. If that script run succeeds, run the function(s) directly, (with props if present?). 
    - If the function succeeds, return any produced string (HTML) in the response.
    - If the function fails, return the 500-error message.
  B. If the script fails, return a 422-error message.

3. If id (and optionally hash) is present, create a key by concatenating id+hash and check if any function has previously been cached at that key. 
  A. If cached, run the cached function (with props?).
      - If the function succeeds, return any produced output (and ignore any script param).
      - If the function fails, remove the function from the cache and return the 500-error message.    
  B. If not cached: is any script param present?
      - If script param: check if that id has been cached before on a different hash. If so, delete those. Then run the script to produce (a) ready-to-run function(s) in nashorn.
          - If the script run succeeds, cache the function at the id+hash key, and then run the function (with props?).
              - If the function succeeds, add the function to the cache @id+hash, and then respond with the output.
              - If the function fails, respond with the 500-error message.
          - If the script run fails, return a 422-error message.
      - If no script param: respond with a 404-error message (resource identified by id was not found)
 
Returns:
- On successful rendering: { status: 200, contentType: text/html, body: produced output (rendered HTML) }
- On argument failure, including errors during the function-creating script run: { status: 400, contentType: text/plain, body: error message }
- On function runtime failure: { status: 500,  contentType: text/plain, body: error message }

Response status codes:
200: OK, look in the body for rendered result.
400: Param error: script or id are needed, both are missing.
404: No function found at the requested id(+hash), and no script param to run
422: The script that was supposed to produce a nashorn function failed
500+: Runtime error during function

Being an API description, this later enables alternative / external rendering servers to be created along the same pattern, and react4xp will be able to communicate with those by simply replacing the service URL.

**Comment by alansemenov** [comment]
Not relevant
