### ISSUE TITLE
Make lib-react4xp use app-react4xp-ssr

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#154]
lib-react4xp should defer SSR to a separate app. Suggested: communicate with server-to-server HTTP (later add direct OSGI communication instead, for in-XP communication), using the API drafted here: #153 :

On rendering: 
- determine from jsxPath what the paths of the necessary dependencies are (chunks, other entries). Add those to an `ids` array along with the inital entry asset, by order of dependency so that the initial entry is last (and setup/runOnce dependencies come first).
- for each of those asset `id`'s in the `ids` array:
  - Use performant way to determine if the asset resource has been updated (in devmode, this can happen after app restart/update).
    - If updated/new, read it into a `script` string, create a content `hash` from it, save/update the hash in an id -> hash cache.
    - If not, read the hash from the hashCache.
  - Send to app-react4xp-ssr:
    -the id, hash, script if updated/new, and props if the id is the initial entry
  - Handle response using the error codes and body.

**Comment by espen42** [comment]
This can be optional: split the actual rendering: app-react4xp-ssr uses a new lib-react4xp-ssr. Then, a client react4xp app can config a rendering-app service URL (to app-react4xp-ssr or any other service that follows the API defined in #153), and if that's missing, use lib-react4xp-ssr itself - the way it is today, keeping backwards compatibility and simplicity intact while offering app-react4xp-ssr (or other, self-made rendering services) as an option, to increase performance.

**Comment by espen42** [comment]
@rymsha : about this part...

_Use performant way to determine if the asset resource has been updated (in devmode, this can happen after app restart/update). If updated/new, read it into a script string_

...what's the best way to do that?

**Comment by ComLock** [comment]
This issue is still under design consideration.
