### ISSUE TITLE
Bug: first rendered view of an entry in Content Studio dev mode is "sticky"

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#19]
After a first (SSR) rendering of an entry in Content Studio in dev mode, changing entry code or input props has no effect inside Content Studio. Live view does update, though.

Cache related problem?

**Comment by espen42** [comment]
Fixed in version 0.3.6

**Comment by gilmarllen** [comment]
I'm testing/learning the react4xp starter, and I noted that for several changes in the jsx files I need to re-build all the project to see the changes, even starting the sandbox in dev mode. Is there a way to handle better it or is it expected behavior for the current implementation of the react4xp?

**Comment by espen42** [comment]
Hmm, this is expected to work. You shouldn't need to rebuild _everything_, but you will need to compile the changed source files into /build/ before dev mode can pick up the changes. 

I'm currently in the middle of updating react4xp, including the starter (approaching a version 1.0.0 - stay tuned! 😉), so just based on my memory of the slightly older version: it's probably the task `webpack_react4xp` in build.gradle that does this. After building the project the first time, you could try to run that task in continuous mode (`gradlew webpack_react4xp -t` I think should do the trick), and leave that running in the background.

**Comment by gilmarllen** [comment]
I see. I'll try to use the -t flag. Thanks and good luck in the updating.
