### ISSUE TITLE
Why is the folder called react4xp/_components/?

### ISSUE THREAD

**Issue by sigdestad** [enonic/lib-react4xp#2]
Is this due to a convention in React, or for other reasons?

**Comment by espen42** [comment]
Mostly to mark it as a magic folder with a specific purpose. If a user puts react components or other JS code directly in react4xp/ or other subfolders than react4xp/_components, they will not be interpreted as usable entries, and won't be directly usable but must be imported by entries (code imported from the react4xp/ root will be included in each transpiled entry, while code imported from react4xp/mySubfolder will become the dependency chunk mySubfolder.<hash>.js.

See https://github.com/enonic/lib-react4xp-runtime#how-to-control-your-entrychunk-structure

**Comment by espen42** [comment]
Fixed in https://www.npmjs.com/package/react4xp-buildconstants/v/0.7.3
