### ISSUE TITLE
Is the .render behavior too magically decided by request now?

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#217]
`.render` ([API](https://developer.enonic.com/docs/react4xp/master/api#react4xp_render)) is meant to be a convenient and safe way to use react4xp: basically, `.render` will always render a visualization (static or active, or an error message), and never risk intervening with Content Studio frontend functionality (either causing breaking errors in code or just disturbing the UX).

Beyond this, the behavior is determined by whether or not a `request` option is added. In order to actually activate the react components in the client, and also to allow the `clientRender` option, the `request` argument must be added and the viewing must be _outside of CS_!

**Behavior overview** of `.render`: 
- **Supplying** `request` detects context (inside or outside of Content Studio) and controls behavior accordingly:
    - In-CS: always-SSR, suppress rendering of JS-pagecontributions (dependencies and trigger call, so the visualization is not activated, only static HTML). 
    - Out-of-CS: optional `clientRender`, render all pagecontributions so the component is active. 
- **Leaving it out** (`request` is undefined/null): no context detection, _always_ render in the "In-CS" mode: SSR without JS pageContributions, so it will _never_ client-activate the react components, only visualize them. 

**"Custom flow"** on the other hand ([API](https://developer.enonic.com/docs/react4xp/master/api#rendering_methods)) is intended as a more "raw", low-level option, leaving more to developers in terms of risk and control. But `request` still makes a difference:
- **Supplying** `request` in both `.renderBody` and `.renderPageContributions` still detects context and controls behavior the same way as for `.render` above.
- **Leaving it out**: 
    - `.renderBody` allows `clientRender` in all contexts (risks empty visualization in CS)
    - `.renderPageContributions` renders JS pagecontributions in all contexts (risks intervening with CS)

(Side note: is all this the best behaviour pattern?)

Also, interaction with error reporting: for both `.render` and "custom flow", server-side **error messages are only rendered** in the error container, and output in the console, if `request` is supplied and the view mode is no "live".

**Either way, this is not super intuitive, breaks the principle of least surprise.**

Simplify the behavior, less dependent on `request`, and expose new options for clarity? 
- `ssrOnly` option for skipping `.renderPageContributions` entirely (saving a bit of processing)? 
- `suppressJS`?
- `suppressTrigger`, for suppressing only the activating trigger call but leaving in all other parge contributions? 
- Or even `overrideTrigger`, which could be empty for suppression, or contain a string, enabling users to write clientside `render`/`hydrate` triggers of their own, for example when sharing data sources (redux etc) across multiple entries (which are separate react apps)?

If these are worth pursuing, also redecide new behavior of request-less `.render`, and whether or not this will be (worth) a breaking change.

**Comment by espen42** [comment]
This behavior overview should be doc'ed!

**Comment by ComLock** [comment]
We have added settings for ssr and hydrate. We will always default to SSR without hydration when the request mode is unknown.
