### ISSUE TITLE
Better source code structure #3: handling imported chunks

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#22]
Dependency chunks should be possible to import from elsewhere, and even already exist in a already-compiled form (e.g. through NPM), and not be neccessary to put in react4xp/ (...chunks/).

This might already work, look closer at this.

**Comment by espen42** [comment]
Related: https://github.com/enonic/starter-react4xp/issues/5

**Comment by espen42** [comment]
Adjacent issue: https://github.com/enonic/lib-react4xp/issues/102

**Comment by ComLock** [comment]
Will be fixed by https://github.com/enonic/lib-react4xp/issues/778
