### ISSUE TITLE
use styled systems / styled component with React4xp

### ISSUE THREAD

**Issue by lienas** [enonic/lib-react4xp#221]
**styled systems** generates styles dynamically for each component.
For **SSR** it is necessary to add the styles to the head for first render as described here:[https://styled-components.com/docs/advanced#server-side-rendering]( https://styled-components.com/docs/advanced#server-side-rendering).

As parts and pages run in different contexts, probably this has to be done in each part or page.
I tested with the following (hard-coded) code:

part-controller:
```
return React4xp.render(
        'HelloWorld',
        props,
        request,
        {
            pageContributions: {
                headEnd: [
                    "<style data-styled=\"true\" data-styled-version=\"5.3.0\">.bQjiFM{color:#cd9200;background-color:purple;}/*!sc*/\n" +
                    "data-styled.g1[id=\"sc-bdnxRM\"]{content:\"bQjiFM,\"}/*!sc*/\n" +
                    "</style>"
                ]
            },
            clientRender: false
        }
    );
```

The style was extracted and logged  in the  component `HelloWorld`  with the following code (for full code see repo-link at the end) :

```
const html = renderToString(sheet.collectStyles(<Box color='#cd9200' bg='purple'/>));
const styleTags = sheet.getStyleTags();
console.log("Fetched styles: ", styleTags);
```

This generates the following html-code:

```
<head>
     <meta charset="UTF-8">
     <title>Test Starter</title>
     <style data-styled="true" data-styled-version="5.3.0">.bQjiFM{color:#cd9200;background-color:purple;}/*!sc*/ data-styled.g1[id="sc-bdnxRM"]{content:"bQjiFM,"}/*!sc*/
      </style>
</head>
```
and after first render the style is replaced with:
`<style data-styled="active" data-styled-version="5.3.0"></style>`

**The requirement is to extract the style in the part opr page controller and add it to the head via React4xp.render()**

The DEMO-APP is available here: [https://github.com/lienas/react4xp2test](https://github.com/lienas/react4xp2test)

**Comment by espen42** [comment]
Hi! I'll take a look when I get the opportunity, probably next week, and investigate how easy this will be to mitigate.

**Comment by lienas** [comment]
switched to next xp
