### ISSUE TITLE
Align nashorn default SSR init settings with XP nashorn settings?

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#222]
XP itself initializes the nashorn engine with:
```
new NashornScriptEngineFactory().getScriptEngine( new String[]{"--optimistic-types=false", "--global-per-engine", "-strict", "--language=es6", "--no-deprecation-warning"})
```

Use the same settings for the react4xp renderer(s)? 

By default? Easily selectable? Only comment in guide and/or react4xp.properties?

**Comment by rymsha** [comment]
Preferred engine is now GraalJS. No need to invest much in Nashorn
