### ISSUE TITLE
jsxPath improvements

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#23]
- Instead of having to manually extrapolate the jsxPath strings, there should be a `getJsxPath()` function
- That function should support relative paths, maybe the standard XP `resolve` function.
- `entryPath` is a better name

**Comment by espen42** [comment]
Duplicated: https://github.com/enonic/starter-react4xp/issues/7

**Comment by ComLock** [comment]
Nice to have, but do we really need to spend time on this? No.
