### ISSUE TITLE
Add support for XP regions in Pages and Layouts

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#27]
An Entry used in an XP Page or Layout should be able to contain and handle XP Regions. 

This may possibly allow JSX-only projects (no Thymeleaf), if needed.

**Comment by espen42** [comment]
The combination of NPM packages react4xp-buildconstants@0.7.10+ and react4xp-build-components@0.3.11+ adds support for using optional JSX from a new and optional package: react4xp-templates(@0.1.8+). 

react4xp-templates currently offers `Region`, `RegionRange` and `Page` components, where Page is an entry and Region/RegionRange must be imported from a react component. Using Page, or importing Region/RegionRange to your own JSX page template, makes it pretty easy to create zero-thymeleaf page templates.

Also, lib-react@0.3.9+ adds `renderPageBody`, which simplifies it even more: one function that takes a `content` argument and returns a (server-side-)rendered HTML from a local/same-name-as-page-controller JSX, or if that's missing: react4xp-templates/Page.

If Layouts are similar, this should be complete shortly.

**Comment by espen42** [comment]
react4xp-templates@0.1.10 and lib-react4xp@0.3.10 adds similar support for layouts.

**Comment by sigdestad** [comment]
What is "RegionRange". And, do you have an example of how to use these new features?

**Comment by espen42** [comment]
RegionRange is the react-component that collects/renders all the Regions in a page or layout as defined in the XML (and their dropped-in components).

**Comment by espen42** [comment]
Examples: 

The default page in the starter, https://github.com/enonic/starter-react4xp/tree/master/src/main/resources/site/pages/default uses the entry https://github.com/enonic/react4xp-templates/blob/master/src/_entries/react4xp-templates/Page.jsx 

And the demo-layout, https://github.com/enonic/starter-react4xp/tree/master/src/main/resources/site/layouts/demo-layout uses its own local entry.
