### ISSUE TITLE
Caching of page contributions sometimes causes errors

### ISSUE THREAD

**Issue by Glenruben** [enonic/lib-react4xp#284]
We use react4xp renderPageContributions to insert the relevant bundles into our page. 
However, when the path to the page contributions has been cached on a path that is not accessible to the current user, for instance in previewing a content, the cached URL can fail with a 401 unauthorized or 404 not found. 

For example: User 1 edits and previews a content. The preview url for the content is https://i.utv.ssb.no/xp/admin/site/preview/default/draft/ssb/befolkning/folketall/statistikk/befolkningen-pa-svalbard and the path for the react4xp bundle is cached. 
Later, User 2 wants to visit an internal tool page that they can access, but they do not have permissions to preview the content that user 1 has visited. The react4xp bundle url points to https://i.utv.ssb.no/xp/admin/site/inline/default/draft/ssb/befolkning/folketall/statistikk/befolkningen-pa-svalbard/_/service/mimir/react4xp-client/ and the page will not load. 

Not exactly sure how to fix the issue, but I assume it originates from resource caching in index.es6, or possibly here: https://github.com/enonic/lib-react4xp/blob/f064db197fc11d329a0d89f8ced4ee12a22e3148/src/main/resources/lib/enonic/react4xp/pageContributions.es6#L86

**Comment by espen42** [comment]
Hi! Thanks for reporting this issue, I'll look at it when I have the opportunity - probably next week.

- Espen Norderud

**Comment by espen42** [comment]
New version of the fix pre-released for testing
