### ISSUE TITLE
Frontend: real choice between react4xp-runtime-externals or CDN

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#3]
The NPM package _react4xp-runtime-externals_ provides an optional webpack step that, when run from build.gradle, compiles a chunk _react4xp.(HASH).externals.js_. This chunk is run in Nashorn when initializing the serverside rendering engine. But it can also be run in the client, providing React and ReactDOM, which is needed by the react4xp client. The _react4xp.(HASH).externals.js_ chunk can be downloaded from the service _react4xp-externals_ (again, iff the _react4xp-runtime-externals_ step is run in build.gradle).

Currently, when fetching the dependencies for an entry, the externals service url is included. This collides with the best-practice of serving React or React4xp from a CDN or a webjar. This should be unravelled: leave the call to the _react4xp-externals_ service to be a manual option, instead of an assumed dependency.

Targets the runtime lib: 
/lib/enonic/react4xp/dependencies.es6 .getAllUrls
/lib/enonic/react4xp/index.es6 .render/.renderSafe (etc)
Generally when building the pageContributions)

**Comment by espen42** [comment]
Related: https://github.com/enonic/starter-react4xp/issues/5

**Comment by ComLock** [comment]
Move serveExternals from render options, to app.cfg. And document it, and provide an example?

**Comment by ComLock** [comment]
Rename to react4xp.serveGlobals app.cfg file

**Comment by ComLock** [comment]
Will be fixed by https://github.com/enonic/lib-react4xp/issues/778
