### ISSUE TITLE
Entries from other libraries not built 

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#301]
When creating entries (and more?) not in the host XP app but in XP libraries consumed by a main app (which uses react4xp), those  entries are not detected at buildtime, and therefore don't become available in _entries.json_, _stats.components.json_ etc.

Find out if this is solved by a particular setup in the host XP app, or requires updates to lib-react4xp (and/or the _react4xp.gradle_ setup in react4xp-npm) to work.

**Comment by espen42** [comment]
Solving this is not trivial. Problem summary:

The react4xp runtime uses the files _entries.json_ and _stats.components.json_ to detect which dependency chunks are required by each entry, in addition to the entry's assets. These json files are created by webpack at buildtime - a process that is triggered by a gradle task, but strictly speaking outsourced to node.js. They are records of the import chain of JS modules, as resulting from webpack's bundling. This probably "locks" the JSX compilation step: it must be done with webpack the way it is now. And so far I don't know any way for webpack to use resources from inside a lib's jar, at buildtime.

One workaround could be to leave the compilation of the lib's entries to the lib itself, let it supply its own _entries.json_ and _stats.components.json_ in its jar file but in a different folder (to avoid namespace collision with the ones from the consuming project), and then, when starting the app, reading them all and merging them to one object (or temporary file).

 Or using NPM instead of a lib (it's already supported to add entry files under node_modules).

**Comment by ComLock** [comment]
If you want to share React code, just make an npm module.
