### ISSUE TITLE
Webpack watch: watch:reactxp missing required CLI arguments

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#346]
After fixing package.json typos (#345), **running the `watch:react4xp` NPM script (part of `watch`) still fails**:
```
ERROR in ./node_modules/react4xp-regions/entries/react4xp-regions/Layout.jsx 1:25-59
Module not found: Error: Can't resolve 'prop-types' in '/Users/<x>/react4xp/node_modules/react4xp-regions/entries/react4xp-regions'

ERROR in ./node_modules/react4xp-regions/entries/react4xp-regions/Layout.jsx 1:59-105
Module not found: Error: Can't resolve 'react4xp-regions/Regions' in '/Users/<x>/react4xp/node_modules/react4xp-regions/entries/react4xp-regions'

ERROR in ./node_modules/react4xp-regions/entries/react4xp-regions/Page.jsx 1:25-59
Module not found: Error: Can't resolve 'prop-types' in '/Users/<x>/react4xp/node_modules/react4xp-regions/entries/react4xp-regions'

ERROR in ./node_modules/react4xp-regions/entries/react4xp-regions/Page.jsx 1:59-105
Module not found: Error: Can't resolve 'react4xp-regions/Regions' in '/Users/<x>/react4xp/node_modules/react4xp-regions/entries/react4xp-regions'

ERROR in ./src/main/resources/site/pages/default/default.jsx 1:97-143
Module not found: Error: Can't resolve 'react4xp-regions/Regions' in '/Users/<x>/react4xp/src/main/resources/site/pages/default'

5 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
```
Comparing with the corresponding (non-watch, but working) gradle task `react4xp_components`: the `react4xp_components` task adds a `--env ROOT=...`  CLI argument, where the value is the project root directory, supplied by gradle. If _react4xp.properties_ adds any `chunkDirs` or `entryDirs` arguments, then gradle extracts those too and adds those as CLI arguments `--env CHUNK_DIRS=...`  and `--env ENTRY_DIRS=...` . The `watch:react4xp` script is missing those.

**Suggested workaround** (although see below): use npm's `--` syntax to add the extra CLI arguments, in double quotes, eg: 

`npm run watch -- --env ROOT="$(pwd)"`

**Comment by ComLock** [comment]
We don't support watch for now.
