### ISSUE TITLE
Webpack watch: compiled changes during webpack doesn't work

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#347]
Even after changing the `watch:react4xp` task and fixing error messages (#346), not everything works.
Example:
```
"watch:react4xp": "webpack --env REACT4XP_CONFIG_FILE=build/react4xp_constants.json ROOT=\"$(pwd)\" ENTRY_DIRS=\"myEntries\" CHUNK_DIRS=\"shared\" OVERRIDE_COMPONENT_WEBPACK=\"webpack.config.react4xp.js\" --config node_modules/react4xp-build-components/webpack.config.js --watch",
```

- It looks like watching changes in files from the directory specified in CHUNK_DIRS do not work.
- _.scss_ files do not seem to be watched.
- With serverside rendering, changes from watch are only shown in edit mode, and not in the previews.

**Comment by espen42** [comment]
This is potentially tricky. 

Find out: are chunkdirs and scss files compiled (to _build/resources/main/assets/react4xp_) when starting up webpack with watch - but not part of what webpack watches, so changes aren’t recompiled? Or are the compiled files actually updated under build/, but not picked up by react4xp?

In the first case, it should be possible to control where webpack watches. 

The second case might be harder, and may actually apply either way. Compiled dependency chunks are both cached, tracked, and hashed in the filename for cache busting (which makes the filename change on content changes, requiring re-tracking, re-caching etc). Making that auto-update while watching will probably involve some careful rewriting of a fair amount of code. And that’s just client-side - making server-side rendering pick it up will probably require something even deeper. This is most likely the issue with different behaviour in different view modes in and outside of content studio.

**Comment by sigdestad** [comment]
Would introducing lib-static simplify things?

**Comment by espen42** [comment]
Worth checking, but my gut feeling: at best, not much.

**Comment by ComLock** [comment]
We don't support watch for now.
