### ISSUE TITLE
React hooks don't work (possibly other recent react features?)

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#35]
Unable to run entries that use react hooks. This _might_ be a problem with multiple and colliding versions of react being used across the react4xp build. Eliminate this.

**Comment by espen42** [comment]
Tried making a minimal example. Posted it as a question at facebook/react's own forum: https://github.com/facebook/react/issues/13991#issuecomment-669171027

**Comment by espen42** [comment]
Solved. Not a bug, but a strict usage requirement that's already covered in the docs, but only mentioned for classes, not function components with hooks.

Turns out the way a functional component is called is extra important when a functional component uses hooks. A function component with hooks that exports JSX must be called as a react component. And since the trigger call in react4xp-runtime-client happens in vanilla JS, any entry that uses hooks must wrap that in a function component _at the export level_.

JSX entry examples:

**1. No hooks, straight export. Works. **
```
const Header = () => {
  return <pre>Header</pre>
};

// Straight function export, will be called from client equivalent to: Header()
export default Header;
```

**2. Hooks, straight export. Does NOT work.**
```
const Header = () => {
  // Using hooks:
  const [count, setCount] = React.useState(0);  

  return <pre>Header</pre>
};
export default Header;
```

**3. Hooks, wrapped export. Works.**
```
const Header = () => {
  // Using hooks:
  const [count, setCount] = React.useState(0);  

  return <pre>Header</pre>
};

// Export wrapped in props => component function. 
// This converts Header from a regular JS function that returns a react component, 
// to an actual functional component. 
// Hence, we cover the following "rule of hooks": 
// Call them at the top level in the body of a function component.  

export default () => <Header />;                                 // <-- SOLUTION!
```

**Comment by espen42** [comment]
Adding a usage emphasis on https://developer.enonic.com/templates/react4xp/master/entries.

**Comment by MohamedMakdoudi** [comment]
i have the same problem as @espen42 can someone help me please

@espen42 your solution doesn't work for me

**Comment by espen42** [comment]
@MohamedMakdoudi Could you please supply a bit more info - what have you tried, specifically how does it fail? If possible, some code? Thank you! :)

**Comment by MohamedMakdoudi** [comment]
Hi @espen42 
I have a project react version 15.6.2 I will update it to version 16.13.1.
and the latter it uses another porjet react version 16.13.1.
So if I create a component type function without using hooks it works fine, and when I call import what hooks a mistake this product

**example:**
import React, {useState} from "react";

const Test = () => {
    const [count, setCount] = useState(0);

    return <pre>Header</pre>
};

export default () => <Test />;

Package.json
<img width="338" alt="Capture d’écran 2020-10-20 à 13 31 47" src="https://user-images.githubusercontent.com/17656729/96580470-9d866a80-12d8-11eb-8a13-23ef2d5e61dc.png">

**Comment by espen42** [comment]
React > 16.8 is necessary, yes.

The code so far looks okay yo me. Where and how does it fail / do you get any error message in the build log, XP server log or in the browser console?

**Comment by espen42** [comment]
Also remember that react hooks require that you're only using one instance of react at a time - in addition to the other [rules of hooks](https://reactjs.org/docs/hooks-rules.html), where your project structure may be relevant. It sounds a little bit like you're having parallel (or nested?) react projects? If so, be careful not to mix them up in the global namespace, etc.

**Comment by MohamedMakdoudi** [comment]
Thank you for your responsiveness @espen42 

yes I have an error message at the console
<img width="866" alt="Capture d’écran 2020-10-20 à 13 44 50" src="https://user-images.githubusercontent.com/17656729/96581649-6fa22580-12da-11eb-9b1c-48dae42c1af2.png">

**Comment by MohamedMakdoudi** [comment]
yes I am using another project which contains basic components but with the same version of react 16.13.1

**Comment by espen42** [comment]
Thanks! You've done the export of your `Test` component correctly, it looks like, so if that's the only component you're rendering here, it does sound like the problem is related to the rules of hooks being broken somewhere - have you been through the troubleshooting instructions for that in the react hooks documentation? 

In particular, there can only be one _instance_ of react - no more than one react object in play at a time in the browser, or you risk this error - even if two imported react instances have the same version.

**Comment by MohamedMakdoudi** [comment]
Thanks 
if i run npm ls react, here is the result
<img width="1210" alt="Capture d’écran 2020-10-20 à 13 50 01" src="https://user-images.githubusercontent.com/17656729/96582792-1804b980-12dc-11eb-9e63-dc19e112a015.png">

how can i go about doing the test if only one react component i have or two?
and if I have two react component what is the solution?

**Comment by MohamedMakdoudi** [comment]
I tried the test of react and it displays true in the console
<img width="897" alt="Capture d’écran 2020-10-20 à 14 16 24" src="https://user-images.githubusercontent.com/17656729/96584656-d7f30600-12de-11eb-8b06-1e10e755fbad.png">

**Comment by espen42** [comment]
Hmm. What does your XP controller where this is rendered, look like?

**Comment by MohamedMakdoudi** [comment]
MacOs x Catalina version 10.15.6

**Comment by espen42** [comment]
No, I mean the Enonic XP controller where you call `React4xp.render`?

**Comment by MohamedMakdoudi** [comment]
I didn't understand your question
what is the React4xp.render?

**Comment by espen42** [comment]
Are you using react in context of an [Enonic XP](https://enonic.com/platform/enonic-xp) project? If not, I'm afraid this is the wrong forum, and you might want to look here instead: https://github.com/facebook/react/issues/13991 
:)

**Comment by MohamedMakdoudi** [comment]
Hi @espen42 
I solved the problem, we made I have a dependency in my package.json which is not up to date.
I update it and all work fine.
the react error message is not significant.
