### ISSUE TITLE
URI out of scope

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#352]
In lib-react4xp-2.1.0 asset URLs can get generated wrong, yielding for example`<domain>/_/error/400?message=URI+out+of+scope/externals.495d563c3.js` on all compiled react4xp assets for a page.

![image](https://user-images.githubusercontent.com/5279775/154025460-027cc745-f549-47cb-95da-a9561e966a8e.png)

May be related to https://discuss.enonic.com/t/linking-to-content-on-a-different-site/945/2

**Comment by ComLock** [comment]
Not reproducible
