### ISSUE TITLE
Simplify NPM packages

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#362]
Probably no longer any reason to keep NPM packages separately versioned and split up? If the NPM package is unified and single-versioned, it simplifies development and project maintenance a lot.

https://github.com/enonic/react4xp-npm
https://www.npmjs.com/package/react4xp

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/5279775/155987539-b77d34aa-7223-42d2-8ab6-5adce508a9eb.png">

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/5279775/155987580-cae29950-08d7-4e8f-92c3-a7aacfcaab59.png">

**Comment by ComLock** [comment]
- I don't understand, and I suspect there is no need for gradle in order to build the npm packages.
- It feels very wrong to have to install Java in order to build an npm package
- Yes I agree, If all the packages are always installed, there is no point in having more than one package
- And probably things can be moved from the npm packages directly into lib-react4xp (similar to lib-admin-ui in app-contentstudio)

**Comment by espen42** [comment]
> _Those 5 files included in the react4xp npm package are they only used during building of some react4xp app?_
Yes.

> _Both in react4xp and buildcomponents all the build process does is copy files from src to root? Just pust them on root and skip the whole build? (including the need for gradle)._
Agree.

> _Buildcomponents / buildconstants could probably be moved into react4xp (at least here the build uses babel)_
Sure.

> _Runtime externals could probably be moved into react4xp/runtime_
Sure, but I'd prefer react4xp/externals

> _Nashorn polyfills could probably be moved into react4xp/nashorn_
Yes. If not react4xp/nashornpolyfills. It's long, but clear.

> _Client could probably be moved into react4xp/client_
Agree.

> _react4xp-regions has no dependency to react4xp and should be moved out to it's own github repo, and entire build can be removed since it only copies files from src to root._
Agree.

**Comment by espen42** [comment]
Also, package name @enonic/react4xp?

**Comment by ComLock** [comment]
> Also, package name @enonic/react4xp?
Perhaps, I'll look into that last.

**Comment by ComLock** [comment]
## Dependency tree

According to the package.json files:

react4xp depends on all in order to pull them in

Only react4xp depends on
  build-components
  client
  externals
  nashornpolyfills

Nashornpolyfills depends on buildconstants
