### ISSUE TITLE
Error / reporting in server log when rendering an array of HTML elements without container

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#375]
Might not be the easiest thing to fix, but for the record:

An error during serverside rendering, where a JSX entry produced an array of HTML elements at the root level (**without a single container around them** - that's the error here), produces this error message: 

```
c.e.lib.react4xp.html.HtmlInserter
ERROR: [ org.jdom2.input.JDOMParseException ] ...when trying to insert HTML at element with ID 'r4x-5sst2npg' into body:

<section class="xp-part part-variableCardsList container">
    <div class="grid-column grid-4" id="r4x-5sst2npg" />
</section>
```

At the very least, the error message is a bit vague.

**Comment by rymsha** [comment]
https://github.com/enonic/lib-react4xp/pull/679 fixes it
