### ISSUE TITLE
Memory leak during SSR init

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#383]
There seems to be a memory leak during SSR init, probably in the way rendering threads are handled, which may cause memory to fill up when repeatedly redeploying an app (as discussed, @rymsha).

This should be a priority when we soon improve the SSR pipeline.

Note: related support issue:
https://enonic.zendesk.com/agent/tickets/5353

**Comment by rymsha** [comment]
`ServerSideRenderer.isInitialized` never gets to false, even after app restart. So Engines keep using ResourceService provided by invalid bundle.
In a scope of #455 it was fixed . `isInitialized` is no longer static and ServerSideRenderer is referenced only once.
