### ISSUE TITLE
Discuss potential memory issues with dynamicScript "cache"

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-react4xp#400]

**Comment by rymsha** [comment]
If values of cached images don't depend on user input we don't have an issue

**Comment by ComLock** [comment]
??? This has nothing to do with images :)

Every react4xp component, will generate one such dynamic script per usage.
So for example if you use the same part two times on a page, that's two dynamic scripts.
If the props change between two different visitors, thats more dynamic scripts.
On a large website, with many visitiors, the number of dynamic scripts could escalate quickly.

Right now I'm only using a constant object in global scope, so the dynamic scripts will be "cached" until the js file falls out of the pool?

However using a cache, with let's say 1 hour expire time, might be a problem if a browser requests a resource that's no longer in the cache. As long as every html page recaches the dynamic script on every request, those dynamic scripts should always exist in the cache when they are needed.

**Comment by rymsha** [comment]
it does not seem right that user input (props) generates new scripts.
Data and code should be split.
