### ISSUE TITLE
Ensure that developers can add their own nashorn polyfills

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#47]
Just like the buildcomponents config, the nashorn polyfills code should be possible to replace, add to, or manipulate. The foundation for this has been laid down, ensure that it works and document it.

**Comment by espen42** [comment]
See also https://github.com/enonic/lib-react4xp/issues/46#issuecomment-614238645

**Comment by poi33** [comment]
I don't think the user should add polyfills at all. 

Can we add most/necessary polyfills ourselves to get a stable es6 compiling of all files? 
If not, can we set a stable transpiling down to es5? (This will probably take a long time)

The idea is that they can add any 3third party scripts they want and that the application handles compiling of the code.

**Comment by espen42** [comment]
@poi33 : that would be ideal, but at the same time, it sounds too ambitious to me that we should aim for polyfilling out of the box everything from node.js that's missing in nashorn...

So this is intended as a backdoor for whenever users come across any nashorn-unsupported functionality they need to work at the server.

Checked in an actual user project, works. :)

**Comment by espen42** [comment]
Checked in a user project, works:

Added a file at the root of the project - **extraNashornPolyfills.js**:

```
if (typeof Object.assign !== 'function') {
    // Must be writable: true, enumerable: false, configurable: true
    Object.defineProperty(Object, "assign", {
        value: function assign(target, varArgs) { // .length of function is 2
            'use strict';
            if (target === null || target === undefined) {
                throw new TypeError('Cannot convert undefined or null to object');
            }
            var to = Object(target);
            for (var index = 1; index < arguments.length; index++) {
                var nextSource = arguments[index];
                if (nextSource !== null && nextSource !== undefined) {
                    for (var nextKey in nextSource) {
                        // Avoid bugs when hasOwnProperty is shadowed
                        if (Object.prototype.hasOwnProperty.call(nextSource, nextKey)) {
                            to[nextKey] = nextSource[nextKey];
                        }
                    }
                }
            }
            return to;
        },
        writable: true,
        configurable: true
    });
}
```


…and added this in **react4xp.properties**:
`nashornPolyfillsSource = extraNashornPolyfills.js`


But Object.assign IS a thing I think should be supported out of the box:

https://github.com/enonic/react4xp-npm/issues/80
