### ISSUE TITLE
create react4xp gradle plugin

### ISSUE THREAD

**Issue by rymsha** [enonic/lib-react4xp#485]
in should replicate tasks done by

'node_modules/react4xp/react4xp.gradle'
'node_modules/react4xp/npmInstall.gradle'

at the same time remove 
'node_modules/react4xp/updaters.gradle'

This issue came up from https://github.com/enonic/cli-enonic/issues/345

Where it is needed to run `npm` command in order for gradle to find the necessary files for the build.
If developers don't have local `npm` it may be a problem.

Gradle plugin can control node and npm version, too, to depend less on developers' local configuration

**Comment by rymsha** [comment]
There is an open question how this new plugin will interact with gradle node plugin: 
- can it extend or use it?
- maybe we don't need node plugin at all?

**Comment by alansemenov** [comment]
Solved by fixing Gradle build
