### ISSUE TITLE
Occasionally, page refresh is needed to render correctly in content studio

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#50]
Sometimes entries are marked as faulty (with error message placeholder) in content studio but render correctly after a page refresh. So, "false alarms".

Map the extent and circumstances of this behavior.

And fix.

**Comment by poi33** [comment]
This is usually the case when restarting the server. 
It might be related that the server loads some assets twice on the first run. 

It is annoying to refresh, and loading forever in content studio.

**Comment by ComLock** [comment]
Cannot reproduce
