### ISSUE TITLE
Add support for adding response fields in the options argument of React4xp.render

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#53]
`React4xp.render` returns a full XP response object: both `body` and `pageContributions`. If a user wants to add more response fields (e.g. `contentType`, `headers` etc), currently they must do that manually (Object.assign, spread operators or such) before returning the object.

It would be neater if this was part of the last `.render` argument `options`: if XP response fields added here were transferred straight to the rendered object.

**Comment by ComLock** [comment]
This is just a nice to have, but as you say, it's already possible, so not needed.
