### ISSUE TITLE
default jsxPath from component

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-react4xp#6]
getComponent() type and descriptor should be enough to automatically set default jsxPath

**Comment by espen42** [comment]
They're supposed to, if I understand correctly what you mean? What should work but doesn't?

**Comment by ComLock** [comment]
But since the documentation and examples include jsxPath it feels required...

**Comment by espen42** [comment]
Hmm, I've been trying to document that you can choose between component object or jsxpath, both in the object constructor and the shorthand functions... (the first example shows it in a shorthand, at least). Is there somewhere I've missed or should be clearer?
