### ISSUE TITLE
New Rollup Typescript Plugin breaks SSR

### ISSUE THREAD

**Issue by rymsha** [enonic/lib-react4xp#680]
After https://github.com/enonic/lib-react4xp/pull/676 was merged, rollup stopped unwrapping `require` function. Graal/Nashorn don't support require. We need to find a solution.

For now we rolled back plugin update

**Comment by ComLock** [comment]
Note to self:

So I'm assuming the fact Enonic supports "require", has nothing to do with this issue:
https://developer.enonic.com/docs/xp/stable/framework/globals#require

It's about the transpiled code that is loaded into Graal/Nashorn when doing SSR.

**Comment by ComLock** [comment]
An example is nashornPolyfills.js

This should not be there:

```
var Map = require('core-js-pure/actual/map');
```

**Comment by ComLock** [comment]
https://github.com/rollup/plugins/issues/1400

**Comment by ComLock** [comment]
https://github.com/rollup/plugins/discussions/1401
