### ISSUE TITLE
React4xp constructor target id and props

### ISSUE THREAD

**Issue by ComLock** [enonic/lib-react4xp#7]
I would like to set id and props in object construction rather than doing this:

https://github.com/enonic/starter-react4xp/blob/6f12790d551e43feb88ff7132f3ac1710698d8e7/src/main/resources/site/parts/03-customflow-example/03-customflow-example.es6#L29-L36

I see that the constructor code has been made with other ideas in mind:
https://github.com/enonic/lib-react4xp/blob/master/src/main/resources/lib/enonic/react4xp/index.es6#L74-L98

Perhaps the API should be discussed?

**Comment by espen42** [comment]
I'd like a talk about that, yeah.

Primer from my part: the idea was to try to maximize the shortness and readability of the code. So everything that's always mandatory information (where to find the entry using jsxPath or getComponent, and for the "shorthand" functions: the request) are ordinary positional arguments, while everything that's optional and depending on situation is parametrized in the "shorthand" way and built by builder pattern in the object-construction way.
