### ISSUE TITLE
esbuild?

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#82]
Consider [esbuild](https://github.com/evanw/esbuild) as a possible alternative for webpack, since parts of the react4xp build process are abstracted away from enduser developers anyway. Said to be to be orders of magnitude faster than webpack!

- Does it cover everything needed now (e.g. chunking based on custom regex patterns, content hashing to file name, entries.json and stats json output... what else)? 
- Does it cover important future needs?
- Will it in any way hamper developers' extensions to the build?
- Crossplatform?
- Benefit vs work cost to learn it and translate the current build 
- Future support?

**Comment by alansemenov** [comment]
Check out at the new [starter](https://github.com/enonic/starter-esbuild) that @ComLock made. I guess he can help you with some questions as well, when you start working on this.

**Comment by espen42** [comment]
Replaced by recent rollup upgrades.
